apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80          # Service port exposed via ELB
      targetPort: 3000  # React container port
