apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      port: 80          # Service port exposed via ELB
      targetPort: 5000  # Flask container port
