name: Backend — CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - "starter/backend/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv

      - name: Install deps (dev)
        run: pipenv install --dev

      - name: Lint
        run: pipenv run lint
  
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv

      - name: Install deps (dev)
        run: pipenv install --dev
        
      - name: Test
        run: pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build --tag=mp-backend:ci-${{ github.sha }} .
