name: Frontend — CD

on:
  push:
    branches: [ main ]
    paths:
      - "starter/frontend/**" 
  workflow_dispatch:

env:
  REACT_APP_MOVIE_API_URL: "http://localhost:5000"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: "starter/frontend/.nvmrc"
          cache: "npm"
          cache-dependency-path: "starter/frontend/package-lock.json"

      - name: Run Lint
        run: |
          npm ci && npm run lint
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: "starter/frontend/.nvmrc"
          cache: "npm"
          cache-dependency-path: "starter/frontend/package-lock.json"
      - name: Run All Tests
        env:
          CI: true
        run: |
          npm ci
          npm test

  build_and_push:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build (tag with git sha; use build-arg from env)
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL="${REACT_APP_MOVIE_API_URL}" \
            -t mp-frontend:${{ github.sha }} \
            .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag & Push image to ECR
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}     # <acct>.dkr.ecr.<region>.amazonaws.com
          REPO:     ${{ secrets.ECR_REPO_FRONTEND }}      # mp-frontend
          SHA:      ${{ github.sha }}
        run: |
          docker tag mp-frontend:${SHA} ${REGISTRY}/${REPO}:${SHA}
          docker push ${REGISTRY}/${REPO}:${SHA}
          echo "IMAGE_URI=${REGISTRY}/${REPO}:${SHA}" >> $GITHUB_ENV
  
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: [build_and_push]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name movie-cluster --region "${{ secrets.AWS_REGION }}"
          kubectl version --client
          kubectl get ns

      - name: Install kustomize
        run: |
          KUSTOMIZE_VER="5.4.1"
          curl -sSfL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VER}/kustomize_v${KUSTOMIZE_VER}_linux_amd64.tar.gz" \
            | tar -xz -C /usr/local/bin kustomize
          kustomize version

      - name: Set image tag in manifests (kustomize)
        working-directory: starter/frontend/k8s
        env:
          IMAGE_URI: ${{ env.IMAGE_URI }}
        run: |
          # IMAGE_URI was exported by the build_and_push job via $GITHUB_ENV
          echo "Using IMAGE_URI=${IMAGE_URI}"
          # Update the image reference used by kustomization.yaml
          kustomize edit set image frontend=${IMAGE_URI}
          # Show the rendered manifest (for logs)
          kustomize build | head -n 50

      - name: Apply manifests to the cluster
        working-directory: starter/frontend/k8s
        run: |
          kustomize build | kubectl apply -f -
          # optional: wait for rollout
          kubectl rollout status deploy/frontend -n default --timeout=120s

