name: Frontend — CD

on:
  push:
    branches: [ main ]
    paths:
      - "starter/frontend/**" 
  workflow_dispatch:

env:
  REACT_APP_MOVIE_API_URL: "http://localhost:5000"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: "starter/frontend/.nvmrc"
          cache: "npm"
          cache-dependency-path: "starter/frontend/package-lock.json"

      - name: Run Lint
        run: |
          npm ci && npm run lint
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: "starter/frontend/.nvmrc"
          cache: "npm"
          cache-dependency-path: "starter/frontend/package-lock.json"
      - name: Run All Tests
        env:
          CI: true
        run: |
          npm ci
          npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker build (tag with git sha; use build-arg from env)
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL="${REACT_APP_MOVIE_API_URL}" \
            -t mp-frontend:${{ github.sha }} \
            .
