name: Frontend — CD

on:
  push:
    branches: [ main ]
    paths:
      - "starter/frontend/**" 
  workflow_dispatch:

env:
  REACT_APP_MOVIE_API_URL: "http://localhost:5000"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: "starter/frontend/.nvmrc"
          cache: "npm"
          cache-dependency-path: "starter/frontend/package-lock.json"

      - name: Run Lint
        run: |
          npm ci && npm run lint
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: "starter/frontend/.nvmrc"
          cache: "npm"
          cache-dependency-path: "starter/frontend/package-lock.json"
      - name: Run All Tests
        env:
          CI: true
        run: |
          npm ci
          npm test

  build_and_push:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build (tag with git sha; use build-arg from env)
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL="${REACT_APP_MOVIE_API_URL}" \
            -t mp-frontend:${{ github.sha }} \
            .

      - name: Configure AWS credentials
        if: ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != '' }}
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag & Push image to ECR
        if: ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != '' }}
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}     # <acct>.dkr.ecr.<region>.amazonaws.com
          REPO:     ${{ secrets.ECR_REPO_FRONTEND }}      # mp-frontend
          SHA:      ${{ github.sha }}
        run: |
          docker tag mp-frontend:${SHA} ${REGISTRY}/${REPO}:${SHA}
          docker push ${REGISTRY}/${REPO}:${SHA}
          echo "IMAGE_URI=${REGISTRY}/${REPO}:${SHA}" >> $GITHUB_ENV
